In [1]:
from pybaseball import statcast
data = statcast(start_dt='2017-06-24', end_dt='2017-06-27')
data.head(2)

,index,pitch_type,game_date,release_speed,release_pos_x,release_pos_z,player_name,batter,pitcher,events,...,home_score,away_score,bat_score,fld_score,post_away_score,post_home_score,post_bat_score,post_fld_score,if_fielding_alignment,of_fielding_alignment
0,317,CU,2017-06-27,79.7,-1.3441,5.4075,Matt Bush,608070.0,456713.0,field_out,...,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,Standard,Strategic
1,326,FF,2017-06-27,98.1,-1.3547,5.4196,Matt Bush,429665.0,456713.0,field_out,...,1.0,2.0,1.0,2.0,2.0,1.0,1.0,2.0,Standard,Strategic

In [2]:
from pybaseball import standings

In [4]:
data = standings()
print (data)

[                  Tm    W    L  W-L%    GB
1   New York Yankees  103   59  .636    --
2     Tampa Bay Rays   96   66  .593   7.0
3     Boston Red Sox   84   78  .519  19.0
4  Toronto Blue Jays   67   95  .414  36.0
5  Baltimore Orioles   54  108  .333  49.0,                    Tm    W    L  W-L%    GB
1     Minnesota Twins  101   61  .623    --
2   Cleveland Indians   93   69  .574   8.0
3   Chicago White Sox   72   89  .447  28.5
4  Kansas City Royals   59  103  .364  42.0
5      Detroit Tigers   47  114  .292  53.5,                    Tm    W   L  W-L%    GB
1      Houston Astros  107  55  .660    --
2   Oakland Athletics   97  65  .599  10.0
3       Texas Rangers   78  84  .481  29.0
4  Los Angeles Angels   72  90  .444  35.0
5    Seattle Mariners   68  94  .420  39.0,                       Tm   W    L  W-L%    GB
1         Atlanta Braves  97   65  .599    --
2   Washington Nationals  93   69  .574   4.0
3          New York Mets  86   76  .531  11.0
4  Philadelphia Phillies  81   81  .500  16.0
5          Miami Marlins  57  105  .352  40.0,                     Tm   W   L  W-L%    GB
1  St. Louis Cardinals  91  71  .562    --
2    Milwaukee Brewers  89  73  .549   2.0
3         Chicago Cubs  84  78  .519   7.0
4      Cincinnati Reds  75  87  .463  16.0
5   Pittsburgh Pirates  69  93  .426  22.0,                      Tm    W   L  W-L%    GB
1   Los Angeles Dodgers  106  56  .654    --
2  Arizona Diamondbacks   85  77  .525  21.0
3  San Francisco Giants   77  85  .475  29.0
4      Colorado Rockies   71  91  .438  35.0
5      San Diego Padres   70  92  .432  36.0]